"""Production BoTorch BO baseline — the "BO done right" comparator (§9.8 / §12.3).

The WP-E upgrade of the numpy :class:`~rig.baselines.warm_bo.WarmStartedBO`
stand-in: a real BoTorch `SingleTaskGP` + `qLogExpectedImprovement` whose
acquisition is optimized CONTINUOUSLY with `optimize_acqf`, so BO's search
resolution is not capped by a discrete Sobol pool (the M2 re-validation finding
BF-1a). It is the *fair* matched-budget comparator, so it deliberately shares
every fairness knob with the RIG loop + the numpy BO:

- **Identical warm start:** the SAME scrambled-Sobol DoE over the expert-
  constrained ranges, generated by the SAME `RecipeTransform` + campaign seed, so
  the seed batch is bit-identical across arms (§9.2 / §12.3).
- **Identical objective:** minimizes the SAME tolerance-normalized box
  scalarization ``g(x)=‖relu(L−y, y−U)/w‖₂`` (``w`` = per-output box half-width);
  BoTorch maximizes, so the GP models ``f = −g`` (§12.3 like-for-like, BF-1 fix).
- **Identical hit rule / budget / cost:** any recipe in a lot in-spec on the real
  machine counts as a hit; only machine queries count against ``budget``
  (acquisition/GP work is free); returns the SAME
  :class:`~rig.active.loop.Trajectory` so WP-G's difference-in-RMST consumes it.
- **No RIG-only tricks leak in:** the GP models the PLAIN posterior (NOT the
  ``μ−κσ`` pessimistic objective — that is a RIG component ablated in §12.4, and
  handicapping the baseline with it would be an adversarially-refutable artifact).
- **Tuned, not a strawman:** the GP uses the §20.5-current Hvarfner √D dim-scaled
  lengthscale prior (Matérn-5/2 + input Normalize + outcome Standardize), so the
  baseline is neither a strawman nor secretly stronger than RIG.

Scope: continuous recipe spaces (the M2/MBE recipe vars — ``T_heater``,
``film_thickness`` — are all continuous). A compositional (simplex) variable
needs the acquisition optimized in a reparameterized space and raises here; that
is a follow-on. torch/gpytorch/botorch are the ``[torch]`` optional extra and are
imported lazily by ``rig.baselines.__init__`` so ``import rig`` stays torch-free.
"""

from __future__ import annotations

import warnings
from collections.abc import Callable, Mapping, Sequence
from typing import Any

import numpy as np
import torch
from botorch.acquisition.logei import qLogExpectedImprovement
from botorch.acquisition.monte_carlo import qUpperConfidenceBound
from botorch.fit import fit_gpytorch_mll
from botorch.models import SingleTaskGP
from botorch.models.transforms.input import Normalize
from botorch.models.transforms.outcome import Standardize
from botorch.models.utils.gpytorch_modules import get_covar_module_with_dim_scaled_prior
from botorch.optim import optimize_acqf
from gpytorch.mlls import ExactMarginalLogLikelihood
from scipy.stats import qmc

from rig.active.loop import Trajectory
from rig.baselines.warm_bo import _distance_to_box
from rig.interfaces import CompositionalVariable, ContinuousVariable
from rig.inverse.pessimistic import parse_targets
from rig.transforms import RecipeTransform

_DTYPE = torch.double


class BoTorchBO:
    """Continuous-acquisition BoTorch BO to reach a spec (§9.8 / §12.3).

    A drop-in :class:`~rig.eval.m2_sweep` ``MethodFactory``: construct with
    ``(*, machine, in_spec, spec, seed, ...)`` and call ``run() -> Trajectory``.
    ``acquisition="qlogei"`` (default) uses ``qLogExpectedImprovement``;
    ``"qlcb"`` uses ``qUpperConfidenceBound`` on ``f=−g`` (an LCB on ``g``)."""

    def __init__(
        self,
        *,
        machine: Callable[[Mapping[str, float]], np.ndarray],
        in_spec: Callable[[np.ndarray], bool],
        variables: Sequence[ContinuousVariable | CompositionalVariable],
        input_keys: Sequence[str],
        output_keys: Sequence[str],
        spec: Mapping[str, Any],
        cost_recipe: Callable[[Mapping[str, float]], float] = lambda r: 1.0,
        c_batch: float = 0.0,
        budget: int = 40,
        q: int = 4,
        n_seed: int | None = None,
        acquisition: str = "qlogei",
        beta: float = 2.0,
        num_restarts: int = 8,
        raw_samples: int = 128,
        u_bound: float = 5.0,
        seed: int = 0,
    ) -> None:
        self.variables = list(variables)
        for v in self.variables:
            if not isinstance(v, ContinuousVariable):
                raise NotImplementedError(
                    "BoTorchBO supports continuous recipe variables only; a "
                    f"compositional variable ({v.name!r}) needs the acquisition "
                    "optimized in a simplex reparameterization (follow-on WP-E). "
                    "Use WarmStartedBO for compositional spaces."
                )
        self.machine = machine
        self.in_spec = in_spec
        self.input_keys = list(input_keys)
        self.output_keys = list(output_keys)
        box = parse_targets(spec["targets"], self.output_keys)
        self._out_idx = np.array([self.output_keys.index(n) for n in box.output_names], dtype=int)
        self._lower, self._upper = box.lower, box.upper
        self._scale = np.maximum((self._upper - self._lower) / 2.0, 1e-12)  # tol-fair
        self.cost_recipe = cost_recipe
        self.c_batch = float(c_batch)
        self.budget = int(budget)
        self.q = int(q)
        if acquisition not in ("qlogei", "qlcb"):
            raise ValueError(f"acquisition must be 'qlogei' or 'qlcb', got {acquisition!r}")
        self.acquisition = acquisition
        self.beta = float(beta)
        self.num_restarts = int(num_restarts)
        self.raw_samples = int(raw_samples)
        self.u_bound = float(u_bound)
        self.seed = int(seed)
        self._rt = RecipeTransform(self.variables)
        self._flat_keys = [v.name for v in self.variables]
        d = self._rt.dim
        self.n_seed = int(n_seed) if n_seed is not None else max(2 * d + 2, 8)
        # optimize_acqf domain = the SAME reachable set the reference arms search,
        # NOT the full closed box: the seed DoE + WarmStartedBO's continuous
        # refinement + the RIG loop all reach only the box-sigmoid image of
        # u∈[−u_bound, u_bound] (x = lo + (hi−lo)·σ(u)), i.e. a thin margin inside
        # each bound and never the exact edge. Matching it keeps the two BO arms'
        # feasible search domains identical (a strict-fairness fix — else BoTorchBO
        # could reach edge recipes the reference arms cannot).
        s_lo = 1.0 / (1.0 + np.exp(self.u_bound))  # σ(−u_bound)
        s_hi = 1.0 / (1.0 + np.exp(-self.u_bound))  # σ(+u_bound)
        lows = np.array([v.lower for v in self.variables], dtype=float)
        highs = np.array([v.upper for v in self.variables], dtype=float)
        self._bounds = torch.tensor(
            np.stack([lows + (highs - lows) * s_lo, lows + (highs - lows) * s_hi]),
            dtype=_DTYPE,
        )

    # -- shared warm-start / objective / query (identical to WarmStartedBO) -----

    def _recipe_to_x(self, recipe: Mapping[str, float]) -> np.ndarray:
        return np.array([recipe[k] for k in self._flat_keys], dtype=float)

    def _sobol_u(self, n: int, seed: int) -> np.ndarray:
        sampler = qmc.Sobol(d=self._rt.dim, scramble=True, seed=seed)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", category=UserWarning)
            u = sampler.random(max(n, 1))
        return (2.0 * u - 1.0) * self.u_bound

    def _g(self, outcome: np.ndarray) -> float:
        y = np.asarray(outcome, dtype=float)[self._out_idx]
        return _distance_to_box(y, self._lower, self._upper, scale=self._scale)

    def _query(self, recipes: list[Mapping[str, float]]):
        X = np.array([self._recipe_to_x(r) for r in recipes], dtype=float)
        outcomes = [np.asarray(self.machine(r), dtype=float) for r in recipes]
        g = np.array([self._g(o) for o in outcomes], dtype=float)
        cost = self.c_batch + float(sum(self.cost_recipe(r) for r in recipes))
        hits = [bool(self.in_spec(o)) for o in outcomes]
        return X, g, cost, hits

    # -- BoTorch surrogate + continuous acquisition -----------------------------

    def _fit_gp(self, X: np.ndarray, g: np.ndarray) -> SingleTaskGP:
        """Fit a SingleTaskGP to ``f = −g`` (BoTorch maximizes) with input Normalize
        over the flat-key box, outcome Standardize, and the §20.5 Hvarfner √D prior."""
        torch.manual_seed(self.seed)
        train_x = torch.as_tensor(X, dtype=_DTYPE)
        train_y = torch.as_tensor(-g, dtype=_DTYPE).unsqueeze(-1)  # maximize -g
        d = train_x.shape[1]
        gp = SingleTaskGP(
            train_x,
            train_y,
            input_transform=Normalize(d, bounds=self._bounds),
            outcome_transform=Standardize(1),
            # Matérn-5/2 (use_rbf_kernel=False) to match the RIG GP tier's kernel
            # family + the §20.5 Hvarfner √D dim-scaled lengthscale prior. The
            # helper defaults to RBF, so the flag is load-bearing, not cosmetic.
            covar_module=get_covar_module_with_dim_scaled_prior(
                ard_num_dims=d, use_rbf_kernel=False
            ),
        )
        mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            fit_gpytorch_mll(mll)
        return gp

    def _propose(self, gp: SingleTaskGP, best_f: float, k: int, batch_seed: int) -> np.ndarray:
        """Continuously optimize the acquisition over the flat-key box → (k, d)."""
        torch.manual_seed(batch_seed)
        if self.acquisition == "qlogei":
            acqf = qLogExpectedImprovement(gp, best_f=best_f)
        else:  # qlcb: UCB on f=-g ⇔ LCB on g (optimistic for minimization)
            acqf = qUpperConfidenceBound(gp, beta=self.beta)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            candidates, _ = optimize_acqf(
                acqf,
                bounds=self._bounds,
                q=k,
                num_restarts=self.num_restarts,
                raw_samples=self.raw_samples,
            )
        return candidates.detach().cpu().numpy().astype(float)  # (k, d)

    def _x_to_recipes(self, X: np.ndarray) -> list[dict[str, float]]:
        return [{k: float(v) for k, v in zip(self._flat_keys, row, strict=True)} for row in X]

    def run(self) -> Trajectory:
        # §9.2 warm start: the IDENTICAL Sobol DoE the RIG loop + numpy BO use.
        seed_recipes = [self._rt.forward(u) for u in self._sobol_u(self.n_seed, self.seed)]
        X, g, cost, hits = self._query(seed_recipes)
        cumulative = cost
        traj = Trajectory(hit=False, cost_to_target=float("inf"), n_queries=len(seed_recipes))
        traj.cumulative_cost.append(cumulative)
        seed_hit = any(hits)
        traj.per_batch_hit.append(seed_hit)
        if seed_hit:
            traj.hit = True
            traj.cost_to_target = cumulative
            traj.stop_reason = "target met in seed DoE"
            return traj

        gp = self._fit_gp(X, g)
        while traj.n_queries < self.budget:
            k = min(self.q, self.budget - traj.n_queries)
            best_f = float(-np.min(g))  # incumbent of f = −g
            cand_X = self._propose(gp, best_f, k, batch_seed=self.seed + 100 + traj.n_queries)
            batch = self._x_to_recipes(cand_X)

            Xb, gb, cost, hits = self._query(batch)
            cumulative += cost
            traj.n_queries += len(batch)
            batch_hit = any(hits)
            traj.cumulative_cost.append(cumulative)
            traj.per_batch_hit.append(batch_hit)
            if batch_hit:
                traj.hit = True
                traj.cost_to_target = cumulative
                traj.stop_reason = f"target met ({self.acquisition} proposal in-spec on machine)"
                return traj

            X = np.vstack([X, Xb])
            g = np.concatenate([g, gb])
            gp = self._fit_gp(X, g)

        traj.stop_reason = "budget exhausted"
        return traj
